export const ALIAS_GAME__SET_TEAMS_COUNT: "ALIAS_GAME__SET_TEAMS_COUNT" =
  "ALIAS_GAME__SET_TEAMS_COUNT";
export const ALIAS_GAME__CHANGE_PUNISHMENT_MODE: "ALIAS_GAME__CHANGE_PUNISHMENT_MODE" =
  "ALIAS_GAME__CHANGE_PUNISHMENT_MODE";
export const ALIAS_GAME__INIT_TEAMS: "ALIAS_GAME__INIT_TEAMS" =
  "ALIAS_GAME__INIT_TEAMS";
export const ALIAS_GAME__ADD_TEAM: "ALIAS_GAME__ADD_TEAM" =
  "ALIAS_GAME__ADD_TEAM";
export const ALIAS_GAME__REMOVE_TEAM: "ALIAS_GAME__REMOVE_TEAM" =
  "ALIAS_GAME__REMOVE_TEAM";
export const ALIAS_GAME__START_GAME: "ALIAS_GAME__START_GAME" =
  "ALIAS_GAME__START_GAME";
export const ALIAS_GAME__WORD_ANSWER: "ALIAS_GAME__WORD_ANSWER" =
  "ALIAS_GAME__WORD_ANSWER";
export const ALIAS_GAME__SET_TIMER_VALUE: "ALIAS_GAME__SET_TIMER_VALUE" =
  "ALIAS_GAME__SET_TIMER_VALUE";
export const ALIAS_GAME__SET_STATUS: "ALIAS_GAME__SET_STATUS" =
  "ALIAS_GAME__SET_STATUS";
export const ALIAS_GAME__TOGGLE_ANSWER_IS_RIGHT: "ALIAS_GAME__TOGGLE_ANSWER_IS_RIGHT" =
  "ALIAS_GAME__TOGGLE_ANSWER_IS_RIGHT";
export const ALIAS_GAME__CLEAR_ANSWERS: "ALIAS_GAME__CLEAR_ANSWERS" =
  "ALIAS_GAME__CLEAR_ANSWERS";
export const ALIAS_GAME__ADD_SCORE_TO_TEAM: "ALIAS_GAME__ADD_SCORE_TO_TEAM" =
  "ALIAS_GAME__ADD_SCORE_TO_TEAM";
export const ALIAS_GAME__CHANGE_TEAM: "ALIAS_GAME__CHANGE_TEAM" =
  "ALIAS_GAME__CHANGE_TEAM";

export const ALIAS_GAME__CHANGE_ROUND_TIME: "ALIAS_GAME__CHANGE_ROUND_TIME" =
  "ALIAS_GAME__CHANGE_ROUND_TIME";

export const ALIAS_GAME__CHANGE_END_SCORE: "ALIAS_GAME__CHANGE_END_SCORE" =
  "ALIAS_GAME__CHANGE_END_SCORE";
export const ALIAS_GAME__RESTART: "ALIAS_GAME__RESTART" = "ALIAS_GAME__RESTART";

export const aliasGameRoundTimes = [10, 20, 30, 40, 50, 60, 70];

export const aliasGameEndGameScores = [10, 15, 20, 25, 30, 35, 40, 45, 50];
